### ISSUE TITLE
Poner un favicon en la documentacion.

### ISSUE THREAD

**Issue by Sandessat** [scripthubteam/scripthubdocs#13]
No se si soy yo pero no hay un **favicon** en la **nueva documentacion**, solo estoy **diciendo**!

https://prnt.sc/q4quvn

**Comment by Laauuu** [comment]
Estamos al tanto de esto y estamos trabajando para añadir un favicon.
¡Gracias por tu reporte!

**Comment by Sandessat** [comment]
Okay!
