### ISSUE TITLE
Invitación de discord no funciona

### ISSUE THREAD

**Issue by tati1206** [scripthubteam/scripthubdocs#16]
En la pagina https://scripthubteam.github.io/scripthubdocs/docs/indice la invitación de discord de "    ¿Necesitas ayuda con nuestra documentación? Visita nuestro servidor de Discord. Haz clic aquí!", no funciona.

**Comment by wwmon** [comment]
Gracias por el reporte, la invitación será renovada en el próximo merge a master. 
![image](https://user-images.githubusercontent.com/54691517/70017999-c5bc8c00-1595-11ea-8c74-17e0e3fdb56e.png)
